# Generated by Django 4.1.7 on 2024-03-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulpritDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('eyes', models.CharField(max_length=100)),
                ('skin', models.CharField(max_length=100)),
                ('facial_features', models.CharField(max_length=100)),
                ('physcial_features', models.CharField(max_length=100)),
                ('other_details', models.CharField(max_length=100)),
            ],
        ),
    ]
