# Generated by Django 4.1.7 on 2024-03-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_culpritdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('max_capacity', models.IntegerField()),
                ('current_capacity', models.IntegerField()),
                ('remaining_capacity', models.IntegerField()),
            ],
        ),
    ]
