# Generated by Django 4.1.7 on 2024-03-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_shelterhome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointments',
        ),
        migrations.RenameField(
            model_name='culpritdetails',
            old_name='age',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='culpritdetails',
            name='eyes',
        ),
        migrations.RemoveField(
            model_name='culpritdetails',
            name='facial_features',
        ),
        migrations.RemoveField(
            model_name='culpritdetails',
            name='height',
        ),
        migrations.RemoveField(
            model_name='culpritdetails',
            name='other_details',
        ),
        migrations.RemoveField(
            model_name='culpritdetails',
            name='physcial_features',
        ),
        migrations.RemoveField(
            model_name='culpritdetails',
            name='skin',
        ),
        migrations.RemoveField(
            model_name='culpritdetails',
            name='weight',
        ),
    ]
